# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
ladies = Category.create(name: "レディース")
mens = Category.create(name: "メンズ")
baby_kids = Category.create(name: "ベビー・キッズ")
interior = Category.create(name: "インテリア・住まい・小物")
book_music_game = Category.create(name: "本・音楽・ゲーム")
toy_hoby_goods = Category.create(name: "おもちゃ・ホビー・グッズ")
beauty = Category.create(name: "コスメ・香水・美容")
electrical_appliances = Category.create(name: "家電・スマホ・カメラ")
sports_leisure = Category.create(name: "スポーツ・レジャー")
handmade = Category.create(name: "ハンドメイド")
ticket = Category.create(name: "チケット")
bicycle_motorcycle = Category.create(name: "自転車・オートバイ")
other = Category.create(name: "その他")

ladies_tops = ladies.children.create(name: "トップス")
ladies_jacket = ladies.children.create(name: "ジャケット/アウター")
ladies_pants = ladies.children.create(name: "パンツ")
ladies_skirt = ladies.children.create(name: "スカート")
ladies_dress = ladies.children.create(name: "ワンピース")
ladies_shoes = ladies.children.create(name: "靴")
ladies_roomwear = ladies.children.create(name: "ルームウェア/パジャマ")
ladies_legwear = ladies.children.create(name: "レッグウェア")
ladies_cap = ladies.children.create(name: "帽子")
ladies_bag = ladies.children.create(name: "バッグ")
ladies_accessory = ladies.children.create(name: "アクセサリー")
ladies_hair_accessory = ladies.children.create(name: "ヘアアクセサリー")
ladies_small_articles = ladies.children.create(name: "小物")
ladies_watch = ladies.children.create(name: "時計")
ladies_wig = ladies.children.create(name: "ウィッグ/エクステ")
ladies_yukata = ladies.children.create(name: "浴衣/水着")
ladies_suit = ladies.children.create(name: "スーツ/フォーマル/ドレス")
ladies_maternity = ladies.children.create(name: "マタニティ")
ladies_other = ladies.children.create(name: "その他")

mens_tops = mens.children.create(name: "トップス")
mens_jacket = mens.children.create(name: "ジャケット/アウター")
mens_pants = mens.children.create(name: "パンツ")
mens_shoes = mens.children.create(name: "靴")
mens_bag = mens.children.create(name: "バッグ")
mens_suit = mens.children.create(name: "スーツ")
mens_cap = mens.children.create(name: "帽子")
mens_accessory = mens.children.create(name: "アクセサリー")
mens_small_articles = mens.children.create(name: "小物")
mens_watch = mens.children.create(name: "時計")
mens_swimming_wear = mens.children.create(name: "水着")
mens_legwear = mens.children.create(name: "レッグウェア")
mens_underwear = mens.children.create(name: "アンダーウェア")
mens_other = mens.children.create(name: "その他")

ladies_tops.children.create([{name: "Tシャツ/カットソー(半袖/袖なし)"}, {name: "Tシャツ/カットソー(七分/長袖)"}, {name: "シャツ/ブラウス(半袖/袖なし)"}, {name: "シャツ/ブラウス(七分/長袖)"}, {name: "ポロシャツ"}, {name: "キャミソール"}, {name: "タンクトップ"}, {name: "ホルターネック"}, {name: "ニット/セーター"}, {name: "チュニック"}, {name: "カーディガン/ボレロ"}, {name: "アンサンブル"}, {name: "ベスト/ジレ"}, {name: "パーカー"}, {name: "トレーナー/スウェット"}, {name: "ベアトップ/チューブトップ"}, {name: "ジャージ"}, {name: "その他"}])
ladies_jacket.children.create([{name: "テーラードジャケット"}, {name: "ノーカラージャケット"}, {name: "Gジャン/デニムジャケット"},{name: "レザージャケット"},{name: "ダウンジャケット"},{name: "ライダースジャケット"},{name: "ミリタリージャケット"},{name: "ダウンベスト"},{name: "ジャンパー/ブルゾン"},{name: "ポンチョ"},{name: "ロングコート"},{name: "トレンチコート"},{name: "ダッフルコート"},{name: "ピーコート"},{name: "チェスターコート"},{name: "モッズコート"},{name: "スタジャン"},{name: "毛皮/ファーコート"},{name: "スプリングコート"},{name: "スカジャン"},{name: "その他"}])